[package]
name = "lifeguard"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.18"
serde = "1.0.228"
chrono = "0.4.42"
flate2 = "1.1.5"
aws-sdk-s3 = "1.110.0"
aws-config = "1.8.10"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.41"
